[package]
name = "chest"
description = "A multiplatform CLI command organizer"
version = "0.1.0"
authors = ["Wayan-Gwie Lapointe <wayangwie@gmail.com>"]
repository = "https://github.com/Dauthdaert/chest"
license = "MIT"
edition = "2021"
exclude = ["tools/**/*", ".github/**/*"]

[profile.dev.package."*"]
opt-level = 3

[workspace]
members = ["./", "tools/ci"]

[dependencies]
crossterm = "0.27"
tui = { package = "ratatui", version = "0.23" }
tui-input = "0.8"
better-panic = "0.3.0"
async-std = "1.12"
sqlx = { version = "0.7", features = [ "runtime-async-std", "sqlite" ] }
directories = "5.0"
log = { version = "0.4", features = ["std"] }
simplelog = "0.12"
clap = { version = "4.4.6", features = ["derive"] }
promptly = "0.3.1"
