[package]
name = "chest"
version = "0.1.0"
authors = ["Wayan-Gwie Lapointe <wayangwie@gmail.com>"]
license = "MIT"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
crossterm = "0.27"
tui = { package = "ratatui", version = "0.23" }
tui-input = "0.8"
better-panic = "0.3.0"
async-std = "1.12"
sqlx = { version = "0.7", features = [ "runtime-async-std", "sqlite" ] }
directories = "5.0"
log = { version = "0.4", features = ["std"] }
simplelog = "0.12"
