name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.2.0
      - name: CI job
        # See tools/ci/src/main.rs for the commands this runs
        run: cargo run -p ci -- lints

  check-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.2.0
      - name: Build & run tests
        # See tools/ci/src/main.rs for the commands this runs
        run: cargo run -p ci -- test
        env:
          RUSTFLAGS: "-C debuginfo=0 -D warnings"

  check-compiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.2.0
      - name: Check Compile
        # See tools/ci/src/main.rs for the commands this runs
        run: cargo run -p ci -- compile

  check-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1.2.0
      - name: Build and check doc
        # See tools/ci/src/main.rs for the commands this runs
        run: cargo run -p ci -- doc
        env:
          RUSTFLAGS: "-C debuginfo=0"
